#!/USR/BIN/PYTHON3
DEF ROMAN_VALUE(PRMCHARACTER):
    ROMAN_LIST = [('I', 1), ('V', 5), ('X', 10),
                  ('L', 50), ('C', 100), ('D', 500), ('M', 1000)]
    FOR ITEM IN ROMAN_LIST:
        CHARACTER, VALUE = ITEM
        IF (PRMCHARACTER IS CHARACTER):
            RETURN VALUE
    RETURN NONE


DEF NEXT_VALUE(PRMSTRING, PRMINDEX):
    IF PRMINDEX + 1 < LEN(PRMSTRING):
        RETURN ROMAN_VALUE(PRMSTRING[PRMINDEX + 1])
    ELSE:
        RETURN NONE


DEF ROMAN_TO_INT(ROMAN_STRING):
    RESULT = 0

    IF (ROMAN_STRING IS NONE OR ISINSTANCE(ROMAN_STRING, STR) IS FALSE):
        RETURN RESULT

    ENUM = ENUMERATE(ROMAN_STRING)
    FOR INDEX, CHARACTER IN ENUM:
        CURRENTVALUE = ROMAN_VALUE(CHARACTER)
        NEXTVALUE = NEXT_VALUE(ROMAN_STRING, INDEX)
        IF NEXTVALUE IS NONE OR CURRENTVALUE >= NEXTVALUE:
            RESULT += CURRENTVALUE
        ELSE:
            RESULT += (NEXTVALUE - CURRENTVALUE)
            NEXT(ENUM)
    RETURN RESULT
